jobs:
  include:
    - stage: Build macOS App
      os: osx
      before_script:
        # Install and setup macOS python pkg
        - /usr/bin/curl https://www.python.org/ftp/python/3.7.6/python-3.7.6-macosx10.9.pkg -o /tmp/python-3.7.6-macosx10.9.pkg
        - sudo /usr/sbin/installer -pkg /tmp/python-3.7.6-macosx10.9.pkg -target /
        - /Applications/Python\ 3.7/Install\ Certificates.command
        - export PYTHON="/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7"
      env:
        - PYTHON="/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7"
        - PROJECT_PATH=$TRAVIS_BUILD_DIR
      script:
        - /usr/bin/make build-macos
      before_deploy:
        - cd ./dist
        - /usr/bin/zip --symlinks -r HDFM.zip HDFM.app
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        draft: true
        skip_cleanup: true
        file: HDFM.zip
        on:
          all_branches: true
    - stage: Build Windows App
      os: windows
      before_script:
        - choco install python --version=3.7.6
      env:
        - PYTHON="C:\ProgramData\chocolatey\bin\python37.exe"
      script:
        - .\build_scripts\build_windows.bat
      before_deploy:
        - cd .\dist
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        draft: true
        skip_cleanup: true
        file: HDFM.exe
        on:
          all_branches: true
#    - stage: compile linux assets and publish
#      deploy:
#        <<: *deploy_base
#        draft: false
